### ISSUE TITLE
How to do scroll Item Up to down.

### ISSUE THREAD

**Issue by ManojBehera** [smanikandan14/SlotMachine#1]
I am experimenting with this code ..But I can not scrolling up to down its only having features from down to up scrolling.

Please advice me to do it from up to down.

**Comment by smanikandan14** [comment]
You need to modify the scroll() method of WheelView.
public void scroll(int delta) 
- Instead of subtracting the delta from Item's Y position, you need to add the delta to scroll top to bottom.
  item.setPosY(item.getY()-delta);
- Instead of checking if item1 is going out of screen, you need to check for last item.

**Comment by ManojBehera** [comment]
Thanks Mani! I may disturb you again if I get any doubt

On Tue, Dec 16, 2014 at 10:24 PM, Mani notifications@github.com wrote:

> You need to modify the scroll() method of WheelView.
> public void scroll(int delta)
> 
>    -
> 
>    Instead of subtracting the delta from Item's Y position, you need to
>    add the delta to scroll top to bottom.
>    item.setPosY(item.getY()-delta);
>    -
> 
>    Instead of checking if item1 is going out of screen, you need to check
>    for last item.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/smanikandan14/SlotMachine/issues/1#issuecomment-67191634
> .

## 

_Thanks & Regards_,
_Manoj Behera_
_Bangalore_

**Comment by ManojBehera** [comment]
This will help me.  

So many Thanks for your response.

**Comment by ManojBehera** [comment]
Hi ,

Previously this code was not working... becuz scrollDown is always false and else condition is also not working "if (hiddingItemY <= -itemHeight)  is always false". When i try to run the else condition it is only swaping the images not scrolling the wheels.

I am showing only one visible items in the wheel not three items. I have added the delta now as you said. and its scrolling top to down but after one or two items its getting disappear.

Please help. 

if (scrollDown) {
            hiddingItemY = mSlotItems.get(visibleSlotItems - 1).getY();
            if (hiddingItemY <= mViewFullHeight) {
                int j = 0;
                for (int i = 1; i < mSlotItems.size(); i++) {
                    Collections.swap(mSlotItems, j, i);
                    j++;
                }
                resetSlotItemsPositions(scrollDown);

```
        }
    } else {

        hiddingItemY = mSlotItems.get(0).getY();
        if (hiddingItemY <= -itemHeight) {
            int j = 0;
            for (int i = 1; i < mSlotItems.size(); i++) {
                Collections.swap(mSlotItems, j, i);
                j++;
            }               
            resetSlotItemsPositions(scrollDown);

        }

    }
```
